-- Run this SQL in your MySQL database to create the proforma invoice tables

-- Table for proforma invoice main info
CREATE TABLE IF NOT EXISTS tbl_proforma_invoice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    client_id INT NOT NULL,
    currency_id INT NOT NULL,
    invoice_type VARCHAR(50) DEFAULT 'Proforma',
    prepared_by INT NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT,
    FOREIGN KEY (currency_id) REFERENCES tbl_currency_type(currency_id) ON DELETE RESTRICT,
    FOREIGN KEY (prepared_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table for proforma invoice items (products)
CREATE TABLE IF NOT EXISTS tbl_proforma_invoice_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    product_id INT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    unit_id INT NOT NULL,
    quantity DECIMAL(18,2) NOT NULL,
    price DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (invoice_id) REFERENCES tbl_proforma_invoice(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add indexes for better performance
CREATE INDEX idx_proforma_client ON tbl_proforma_invoice(client_id);
CREATE INDEX idx_proforma_currency ON tbl_proforma_invoice(currency_id);
CREATE INDEX idx_proforma_preparer ON tbl_proforma_invoice(prepared_by);
CREATE INDEX idx_proforma_items_invoice ON tbl_proforma_invoice_items(invoice_id);

-- Note: To generate the unique code for each proforma invoice:
--   Format: GIHACHASHTAG{id}-{date}
--   Example: GIHACHASHTAG15-2026-02-14
--   This is automatically generated by the application when creating an invoice.
